/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.josue.oauth.provider.entity;

/**
 *
 * @author Josue
 */
public class OAuthParam {

    //**** Authorize stage
    //the client id
    public static final String CLIENT_ID = "client_id";
    //redirect should always match the registered utl
    public static final String REDIRECT_URL = "redirect_uri";
    //required scope by the client application
    public static final String SCOPE = "scope";
    //An unguessable random string sent by the client. It is used to protect against cross-site request forgery attacks.
    public static final String STATE = "scope";

    //**** Token grant stage
    //The for the Token request (generated by the AuthorizeServlet)
    public static final String CODE = "code";
    //client secret
    public static final String CLIENT_SECRET = "client_secret";
    //Json response fild
    public static final String ACCESS_TOKEN = "access_token";
    //Json response fild
    public static final String REFRESH_TOKEN = "refresh_token";
    //Json response fild
    public static final String EXPIRES_IN = "expires_in";

}
